### ISSUE TITLE
How to change the font of the icons? 

### ISSUE THREAD

**Issue by anilmuppalla** [blackxored/fontello-rails#1]
After gem install, and import the sass files are compiled and stored, so we cannot edit the sass files directly. How can i change the size of the icons in the class value of a tag for that icon?

**Comment by blackxored** [comment]
Hey @mak89k I probably misunderstood you but the point of font icons is that you get to set the size with plain CSS, you can also add text-shadow, box shadow and gradients, all sorts of nifty tricks. What are you intending to do?

**Comment by anilmuppalla** [comment]
I intend to increase the size of the icon.

**Comment by blackxored** [comment]
You can target a specific selector, and then set the font-size property through CSS. Let me know how it goes.

## 

Best Regards,

Adrian Perez
http://www.adrianperez.org (http://www.adrianperez.org/)
Twitter: @blackxored | Skype: blackxored | Google Voice: (559) 744 3201

Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by anilmuppalla** [comment]
Oh yes, Thanks a lot for the help! You have provided an amazing Gem! Keep Up The Great Work.

**Comment by blackxored** [comment]
Thanks.

On Thursday, June 20, 2013, Anil Kumar Muppalla wrote:

> Oh yes, Thanks a lot for the help! You have provided an amazing Gem! Keep
> Up The Great Work.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/blackxored/fontello-rails/issues/1#issuecomment-19784052
> .

## 

Best Regards,

Adrian Perez
http://www.adrianperez.org
Twitter: @blackxored | Skype: blackxored | Google Voice: (559) 744 3201

**Comment by blackxored** [comment]
I'll be closing this issue soon, I don't feel like unpacking my notebook
now. ;)

On Thursday, June 20, 2013, Adrian Perez wrote:

> Thanks.
> 
> On Thursday, June 20, 2013, Anil Kumar Muppalla wrote:
> 
> > Oh yes, Thanks a lot for the help! You have provided an amazing Gem! Keep
> > Up The Great Work.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/blackxored/fontello-rails/issues/1#issuecomment-19784052
> > .
> 
> ## 
> 
> Best Regards,
> 
> Adrian Perez
> http://www.adrianperez.org
> Twitter: @blackxored | Skype: blackxored | Google Voice: (559) 744 3201

## 

Best Regards,

Adrian Perez
http://www.adrianperez.org
Twitter: @blackxored | Skype: blackxored | Google Voice: (559) 744 3201

**Comment by anilmuppalla** [comment]
Please do! Thanks again.

**Comment by blackxored** [comment]
Done. Glad to be helpful.

**Comment by anilmuppalla** [comment]
Thanks again.
