### ISSUE TITLE
How to upgrade

### ISSUE THREAD

**Issue by andreacfm** [blackxored/fontello-rails#2]
Does exists a way to include the latest icons from fontello?

**Comment by blackxored** [comment]
No, I don't currently have an automated process for pulling them down. But we can work on it.

**Comment by andreacfm** [comment]
What do you think could be the best way to approach it.
I'd like to help if possible.

Andrea

On Jun 25, 2013, at 11:25 PM, Adrian Perez notifications@github.com wrote:

> No, I don't currently have an automated process for pulling them down. But we can work on it.
> 
> —
> Reply to this email directly or view it on GitHub.

Andrea Campolonghi
acampolonghi@gmail.com

**Comment by blackxored** [comment]
I'm taking a look at this starting next week. I'll keep you posted. Thanks. 
—

**Comment by anilmuppalla** [comment]
Hi, 

for rails 4.0 the dependencies don't match.

fontello-rails requires railties 3.2.9 while railties 4.0.0 is used for others

**Comment by blackxored** [comment]
@4ni1 I fixed this just now.
@everyone: Been busy, but I'll take a look at the remaining stuff on the plate.
